version: '3'

networks:
  monitoring:

services:
  influxdb:
    container_name: influxdb
    image: influxdb:2.7.1
    security_opt:
      - no-new-privileges:true
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: SomeStrongPas34%^
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: SomeStrongPas34%^
      DOCKER_INFLUXDB_INIT_ORG: defi_stats
      DOCKER_INFLUXDB_INIT_BUCKET: prod
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: r_g71oNQ==
    ports:
      - "8086:8086"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./data/grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    links:
      - influxdb:influxdb
    networks:
      - monitoring

  redis:
    image: redis:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - redis_storage:/redis/data

volumes:
  influxdb-storage:
  grafana-storage:
  redis_storage:

#    env_file:
#      - .env
#    entrypoint: ["./entrypoint.sh"]

